CREATE TABLE `social_terminal` (
  `TABLE_ID` int(11) NOT NULL,
  `NAME` text NOT NULL,
  `EMAIL` text NOT NULL,
  `PASSW` text NOT NULL,
  `START_ID` text NOT NULL,
  `NOW_ID` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `social_terminal`
  MODIFY `TABLE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;
